# Git
branches:
  only:
    - master
    - dev
language: ruby


# Environment
rvm:
 - 2.1
 - 2.2
 - 2.3.2
# - 2.4.0-preview3
services:
 - postgresql
sudo: false
addons:
  apt:
    packages:
    - libgeos++-dev
  postgresql: "9.4"


# Setup
before_install:
  - gem install bundler -v 1.17.3
  - bundle install --without development

before_script:
  - psql -c 'CREATE DATABASE mapotempo;' -U postgres
  - psql mapotempo -c 'CREATE EXTENSION hstore;' -U postgres
  - cp config/database.yml.travis config/database.yml


# Run
script:
  - bundle exec rake test

notifications:
  slack: mapotempo:JU2Tat4AuZkNYkQEtOTbtWGP#git
